### ISSUE TITLE
не пишет ошибки в базу

### ISSUE THREAD

**Issue by AlexTransit** [temoto/venderctl#1]
в логи пишет
`Sep 20 15:11:05 adn venderctl[19718]: sponge.go:72: debug: tele packet=tele.Packet(Kind=Telemetry VmId=1001079 Payload=08f78c3d1a960112930165786563757465206d656e7520636f64653d352070726963653d323330302872617729206e616d653d27d18dd181d0bfd180d0b5d181d181d0be20d181d0be20d181d0bbd0b8d0b2d0bad0b0d0bcd0b8273a206d64622e6576656e642e657370726573736f2e6772696e642f776169742d646f6e652f706f6c6c2d6c6f6f703a206576656e64206572726f72636f64653d36323a00)
Sep 20 15:11:05 adn venderctl[19718]: sponge.go:118: vm=1001079 telemetry=vm_id:1001079 error:<message:"execute menu code=5 price=2300(raw) name='\321\215\321\201\320\277\321\200\320\265\321\201\321\201\320\276 \321\201\320\276 \321\201\320\273\320\270\320\262\320\272\320\260\320\274\320\270': mdb.evend.espresso.grind/wait-done/poll-loop: evend errorcode=62" > stat:<>
`
или
`Sep 20 15:11:05 adn venderctl[19718]: transport-mqtt.go:126: debug: mqtt packet=tele.Packet(Kind=Telemetry VmId=1001079 Payload=08f78c3d1a960112930165786563757465206d656e7520636f64653d352070726963653d323330302872617729206e616d653d27d18dd181d0bfd180d0b5d181d181d0be20d181d0be20d181d0bbd0b8d0b2d0bad0b0d0bcd0b8273a206d64622e6576656e642e657370726573736f2e6772696e642f776169742d646f6e652f706f6c6c2d6c6f6f703a206576656e64206572726f72636f64653d36323a00)`
в базу ничего не пишет.

**Comment by temoto** [comment]
fixed 8597ffb0914aceab1d5e9f9d08462eff102d26d5
